poco: Add pass/fail ststus into logs
Ptests do not report status otherwise on build host

Signed-off-by: Khem Raj <raj.khem@gmail.com>

diff --git a/meta-oe/recipes-support/poco/poco/run-ptest b/meta-oe/recipes-support/poco/poco/run-ptest
--- a/meta-oe/recipes-support/poco/poco/run-ptest
+++ b/meta-oe/recipes-support/poco/poco/run-ptest
@@ -1,8 +1,19 @@
 #!/bin/sh
+i=0
 while read runner; do
   oldpath=`pwd` >/dev/null
   cd bin
   echo Testing $runner
   ./$runner -ignore $oldpath/cppignore.lnx -all
+  export res$((i++))=$?
   cd $oldpath >/dev/null
+done < testrunners
+i=0
+while read runner; do
+  eval assign=\$res$((i++))
+  if [ $assign -ne 0 ]; then
+    echo "FAIL: $runner"
+  else
+    echo "PASS: $runner"
+  fi
 done < testrunners
